image:
  repository: "danielnaumau/github-proxy"
  tag: "57d6c78"
  pullPolicy: IfNotPresent

replicaCount: 2

availability:
  minAvailable: 1

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5